### ISSUE TITLE
code question

### ISSUE THREAD

**Issue by superhero-me** [PKU-ML/ContraNorm#1]
Excuse me, what does this line of code ”adj = adj + adj.T.multiply(adj.T > adj) - adj.multiply(adj.T > adj) + sp.eye(adj.shape[0])“ do in gnn?

**Comment by superhero-me** [comment]
Has this work been tested on larger graphs, such as "ogbn-arxiv" and "ogbn-products"

**Comment by guoxiaojun1999** [comment]
Thanks for your questions. For the line of code "adj = adj + adj.T.multiply(adj.T > adj) - adj.multiply(adj.T > adj) + sp.eye(adj.shape[0])", it ensures the adjacency matrix to be symmetric. For larger graphs, we conduct experiments on  the benchmark ogbn-arxiv, the implementation can be found in this repository [(OGB)](https://github.com/PKU-ML/ContraNorm/tree/main/OGB), and see more discussion in our revised paper [ContraNorm](https://arxiv.org/pdf/2303.06562.pdf).
