### ISSUE TITLE
Equation Deduction

### ISSUE THREAD

**Issue by JasmineCAicai** [PKU-ML/ContraNorm#2]
Hi! I deducted Equation 22 shown in the appendix, but I got a different result.
For the second step, I think there may be two sign typos. Since `lambda` is followed by a higher precedence parenthesis, two substractions should be additions, otherwise, it cannot form a reasonable equivalent substitution with the _P_ mentioned above. 
![screenshot](https://github.com/PKU-ML/ContraNorm/assets/48902911/05283ac9-c10b-46b5-b34b-251cabc2a75c)
For the third step,  I got ![e1](https://github.com/PKU-ML/ContraNorm/assets/48902911/1c0a9b38-52c1-4285-9891-6d16f102ff3e) as the first term, not ![e2](https://github.com/PKU-ML/ContraNorm/assets/48902911/a5e869f2-555a-472c-a8a7-ba2411832b43). 
The attached photo is the procedure. I am not sure whether my deduction is correct.
![deduction](https://github.com/PKU-ML/ContraNorm/assets/48902911/9c736e7b-b75e-48d0-af5d-63b2f23a6c63)

**Comment by rexdu2003** [comment]
Thanks for your questions. There are typos for the second step and subtractions should be additions. For the third step, indeed as you have pointed out, it should be ![image](https://github.com/PKU-ML/ContraNorm/assets/70220060/b3eb3492-999b-4216-9cb9-0c28c9338d09) as the first term. Yet ![image](https://github.com/PKU-ML/ContraNorm/assets/70220060/244c9b95-5f9e-44f8-8ada-b126ee26f3c5) and ![image](https://github.com/PKU-ML/ContraNorm/assets/70220060/50e6a46d-6173-4323-82bf-dcc2c9ff65ef) both have the same value (1-lambda) as the largest eigenvalue, so the conclusion will not change.
